---
abstract: 'a transcription markup syntax for TEI XML'
author:
  - 'Tara L Andrews <aurum@cpan.org>'
build_requires:
  Convert::Number::Armenian: 0
  ExtUtils::MakeMaker: 6.36
  Test::More::UTF8: 0
  Test::Warn: 0
  XML::LibXML::XPathContext: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::TEI::Markup
name: Text-TEI-Markup
no_index:
  directory:
    - inc
    - t
requires:
  XML::LibXML: 0
  perl: 5.008003
resources:
  license: http://dev.perl.org/licenses/
version: 1.9
